min_version = "2024.9.5"

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tools]
python = "{{ get_env(name='PYTHON_VERSION', default='3.13.5') }}"
ruff = "latest"
uv = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
# run = "uv pip install ."
run = "uv pip sync uv.lock"

[tasks.app]
description = "Run the application"
run = "python weather.py"

# [tasks.test]
# description = "Run tests"
# run = "pytest tests/"

[tasks.lint]
description = "Lint the code"
run = "ruff check ./"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''
